### ISSUE TITLE
Fix `to_curve`

### ISSUE THREAD

**Issue by prusse-martin** [ESSS/alfasim-sdk#312]
The PR #297 introduced a change to `to_curve` that ignore the actual input value and return some arbitrary value.

https://github.com/ESSS/alfasim-sdk/pull/297/files#diff-7a60ea37b1d7d1535a0213d2be81a252821cd74c5974ffa478ff784214f0c414R195-R199

**Comment by Gualcar** [comment]
Yes, there is a Jira task created for this topic -> ASIM-5237
